# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(698, 553)
        MainWindow.setMinimumSize(QtCore.QSize(698, 553))
        MainWindow.setMaximumSize(QtCore.QSize(698, 553))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setVerticalSpacing(9)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.TOP_FRAME = QtGui.QFrame(self.frame)
        self.TOP_FRAME.setFrameShape(QtGui.QFrame.StyledPanel)
        self.TOP_FRAME.setFrameShadow(QtGui.QFrame.Raised)
        self.TOP_FRAME.setObjectName(_fromUtf8("TOP_FRAME"))
        self.gridLayout_5 = QtGui.QGridLayout(self.TOP_FRAME)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem = QtGui.QSpacerItem(397, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        self.pb_back = QtGui.QPushButton(self.TOP_FRAME)
        self.pb_back.setMinimumSize(QtCore.QSize(80, 0))
        self.pb_back.setObjectName(_fromUtf8("pb_back"))
        self.gridLayout_5.addWidget(self.pb_back, 0, 1, 1, 1)
        self.pb_clear = QtGui.QPushButton(self.TOP_FRAME)
        self.pb_clear.setMinimumSize(QtCore.QSize(80, 0))
        self.pb_clear.setObjectName(_fromUtf8("pb_clear"))
        self.gridLayout_5.addWidget(self.pb_clear, 0, 2, 1, 1)
        self.screen_LE = QtGui.QLineEdit(self.TOP_FRAME)
        self.screen_LE.setMinimumSize(QtCore.QSize(0, 40))
        self.screen_LE.setObjectName(_fromUtf8("screen_LE"))
        self.gridLayout_5.addWidget(self.screen_LE, 1, 0, 1, 3)
        self.gridLayout_6.addWidget(self.TOP_FRAME, 0, 0, 1, 1)
        self.BOTTOM_FRAME = QtGui.QFrame(self.frame)
        self.BOTTOM_FRAME.setFrameShape(QtGui.QFrame.StyledPanel)
        self.BOTTOM_FRAME.setFrameShadow(QtGui.QFrame.Raised)
        self.BOTTOM_FRAME.setObjectName(_fromUtf8("BOTTOM_FRAME"))
        self.gridLayout_4 = QtGui.QGridLayout(self.BOTTOM_FRAME)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pb_7 = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_7.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_7.setObjectName(_fromUtf8("pb_7"))
        self.gridLayout_4.addWidget(self.pb_7, 0, 0, 1, 1)
        self.pb_8 = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_8.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_8.setObjectName(_fromUtf8("pb_8"))
        self.gridLayout_4.addWidget(self.pb_8, 0, 1, 1, 1)
        self.pb_9 = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_9.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_9.setObjectName(_fromUtf8("pb_9"))
        self.gridLayout_4.addWidget(self.pb_9, 0, 2, 1, 1)
        self.pb_add = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_add.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_add.setObjectName(_fromUtf8("pb_add"))
        self.gridLayout_4.addWidget(self.pb_add, 0, 3, 1, 1)
        self.pb_4 = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_4.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_4.setObjectName(_fromUtf8("pb_4"))
        self.gridLayout_4.addWidget(self.pb_4, 1, 0, 1, 1)
        self.pb_5 = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_5.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_5.setObjectName(_fromUtf8("pb_5"))
        self.gridLayout_4.addWidget(self.pb_5, 1, 1, 1, 1)
        self.pb_6 = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_6.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_6.setObjectName(_fromUtf8("pb_6"))
        self.gridLayout_4.addWidget(self.pb_6, 1, 2, 1, 1)
        self.pb_minus = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_minus.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_minus.setObjectName(_fromUtf8("pb_minus"))
        self.gridLayout_4.addWidget(self.pb_minus, 1, 3, 1, 1)
        self.pb_1 = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_1.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_1.setObjectName(_fromUtf8("pb_1"))
        self.gridLayout_4.addWidget(self.pb_1, 2, 0, 1, 1)
        self.pb_2 = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_2.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_2.setObjectName(_fromUtf8("pb_2"))
        self.gridLayout_4.addWidget(self.pb_2, 2, 1, 1, 1)
        self.pb_3 = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_3.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_3.setObjectName(_fromUtf8("pb_3"))
        self.gridLayout_4.addWidget(self.pb_3, 2, 2, 1, 1)
        self.pb_multiply = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_multiply.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_multiply.setObjectName(_fromUtf8("pb_multiply"))
        self.gridLayout_4.addWidget(self.pb_multiply, 2, 3, 1, 1)
        self.pb_0 = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_0.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_0.setObjectName(_fromUtf8("pb_0"))
        self.gridLayout_4.addWidget(self.pb_0, 3, 0, 1, 1)
        self.pb_dot = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_dot.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_dot.setObjectName(_fromUtf8("pb_dot"))
        self.gridLayout_4.addWidget(self.pb_dot, 3, 1, 1, 1)
        self.pb_equal = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_equal.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_equal.setObjectName(_fromUtf8("pb_equal"))
        self.gridLayout_4.addWidget(self.pb_equal, 3, 2, 1, 1)
        self.pb_divide = QtGui.QPushButton(self.BOTTOM_FRAME)
        self.pb_divide.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_divide.setObjectName(_fromUtf8("pb_divide"))
        self.gridLayout_4.addWidget(self.pb_divide, 3, 3, 1, 1)
        self.pb_divide.raise_()
        self.pb_add.raise_()
        self.pb_multiply.raise_()
        self.pb_7.raise_()
        self.pb_4.raise_()
        self.pb_9.raise_()
        self.pb_minus.raise_()
        self.pb_dot.raise_()
        self.pb_3.raise_()
        self.pb_5.raise_()
        self.pb_equal.raise_()
        self.pb_0.raise_()
        self.pb_6.raise_()
        self.pb_8.raise_()
        self.pb_2.raise_()
        self.pb_1.raise_()
        self.gridLayout_6.addWidget(self.BOTTOM_FRAME, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 698, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Pondi Calculator", None))
        self.pb_back.setText(_translate("MainWindow", "Back", None))
        self.pb_clear.setText(_translate("MainWindow", "Clear", None))
        self.pb_7.setText(_translate("MainWindow", "7", None))
        self.pb_8.setText(_translate("MainWindow", "8", None))
        self.pb_9.setText(_translate("MainWindow", "9", None))
        self.pb_add.setText(_translate("MainWindow", "+", None))
        self.pb_4.setText(_translate("MainWindow", "4", None))
        self.pb_5.setText(_translate("MainWindow", "5", None))
        self.pb_6.setText(_translate("MainWindow", "6", None))
        self.pb_minus.setText(_translate("MainWindow", "-", None))
        self.pb_1.setText(_translate("MainWindow", "1", None))
        self.pb_2.setText(_translate("MainWindow", "2", None))
        self.pb_3.setText(_translate("MainWindow", "3", None))
        self.pb_multiply.setText(_translate("MainWindow", "X", None))
        self.pb_0.setText(_translate("MainWindow", "0", None))
        self.pb_dot.setText(_translate("MainWindow", ".", None))
        self.pb_equal.setText(_translate("MainWindow", "=", None))
        self.pb_divide.setText(_translate("MainWindow", "/", None))

